import { NextResponse } from "next/server"

// 목업 데이터
const mockData = {
  "premier-league": [
    {
      id: 1,
      name: "올리 왓킨스",
      team: "아스톤 빌라",
      teamLogo: "/teams/aston-villa.png",
      assists: 13,
      gamesPlayed: 37,
    },
    { id: 2, name: "파스칼 그로스", team: "브라이튼", teamLogo: "/teams/brighton.png", assists: 13, gamesPlayed: 34 },
    {
      id: 3,
      name: "케빈 데 브라위너",
      team: "맨체스터 시티",
      teamLogo: "/teams/man-city.png",
      assists: 10,
      gamesPlayed: 18,
    },
    { id: 4, name: "부카요 사카", team: "아스널", teamLogo: "/teams/arsenal.png", assists: 9, gamesPlayed: 35 },
    { id: 5, name: "콜 파머", team: "첼시", teamLogo: "/teams/chelsea.png", assists: 11, gamesPlayed: 35 },
    {
      id: 6,
      name: "브루노 페르난데스",
      team: "맨체스터 유나이티드",
      teamLogo: "/teams/man-utd.png",
      assists: 8,
      gamesPlayed: 35,
    },
    { id: 7, name: "모하메드 살라", team: "리버풀", teamLogo: "/teams/liverpool.png", assists: 9, gamesPlayed: 32 },
    {
      id: 8,
      name: "트렌트 알렉산더-아놀드",
      team: "리버풀",
      teamLogo: "/teams/liverpool.png",
      assists: 9,
      gamesPlayed: 29,
    },
    { id: 9, name: "카이 하베르츠", team: "아스널", teamLogo: "/teams/arsenal.png", assists: 7, gamesPlayed: 35 },
    { id: 10, name: "제임스 매디슨", team: "토트넘", teamLogo: "/teams/tottenham.png", assists: 8, gamesPlayed: 27 },
  ],
  "la-liga": [
    {
      id: 1,
      name: "로드리고",
      team: "레알 마드리드",
      teamLogo: "/teams/real-madrid.png",
      assists: 11,
      gamesPlayed: 33,
    },
    {
      id: 2,
      name: "안투안 그리즈만",
      team: "아틀레티코 마드리드",
      teamLogo: "/teams/atletico-madrid.png",
      assists: 10,
      gamesPlayed: 36,
    },
    {
      id: 3,
      name: "이아고 아스파스",
      team: "셀타 비고",
      teamLogo: "/teams/celta-vigo.png",
      assists: 9,
      gamesPlayed: 33,
    },
    { id: 4, name: "브라이언 힐", team: "지로나", teamLogo: "/teams/girona.png", assists: 8, gamesPlayed: 35 },
    {
      id: 5,
      name: "로베르트 레반도프스키",
      team: "바르셀로나",
      teamLogo: "/teams/barcelona.png",
      assists: 8,
      gamesPlayed: 34,
    },
    {
      id: 6,
      name: "비니시우스 주니오르",
      team: "레알 마드리드",
      teamLogo: "/teams/real-madrid.png",
      assists: 9,
      gamesPlayed: 26,
    },
    { id: 7, name: "사비 알론소", team: "바르셀로나", teamLogo: "/teams/barcelona.png", assists: 7, gamesPlayed: 32 },
    { id: 8, name: "알렉스 바에나", team: "비야레알", teamLogo: "/teams/villarreal.png", assists: 7, gamesPlayed: 35 },
    {
      id: 9,
      name: "사무엘 림",
      team: "레알 소시에다드",
      teamLogo: "/teams/real-sociedad.png",
      assists: 7,
      gamesPlayed: 33,
    },
    {
      id: 10,
      name: "페드로 푸에르타스",
      team: "알메리아",
      teamLogo: "/teams/almeria.png",
      assists: 6,
      gamesPlayed: 35,
    },
  ],
  "serie-a": [
    { id: 1, name: "마테오 폴리타노", team: "나폴리", teamLogo: "/teams/napoli.png", assists: 10, gamesPlayed: 35 },
    { id: 2, name: "마르코스 튀람", team: "인테르 밀란", teamLogo: "/teams/inter.png", assists: 7, gamesPlayed: 33 },
    { id: 3, name: "안드레아 콜파니", team: "볼로냐", teamLogo: "/teams/bologna.png", assists: 7, gamesPlayed: 35 },
    { id: 4, name: "파울로 디발라", team: "로마", teamLogo: "/teams/roma.png", assists: 9, gamesPlayed: 28 },
    { id: 5, name: "니콜로 바렐라", team: "인테르 밀란", teamLogo: "/teams/inter.png", assists: 7, gamesPlayed: 34 },
    {
      id: 6,
      name: "페데리코 디마르코",
      team: "인테르 밀란",
      teamLogo: "/teams/inter.png",
      assists: 7,
      gamesPlayed: 32,
    },
    {
      id: 7,
      name: "안토니오 카나드레바",
      team: "사수올로",
      teamLogo: "/teams/sassuolo.png",
      assists: 7,
      gamesPlayed: 33,
    },
    { id: 8, name: "마테오 다르미안", team: "인테르 밀란", teamLogo: "/teams/inter.png", assists: 6, gamesPlayed: 33 },
    { id: 9, name: "라파엘 레앙", team: "AC 밀란", teamLogo: "/teams/milan.png", assists: 6, gamesPlayed: 32 },
    {
      id: 10,
      name: "안드레아 피나몬티",
      team: "사수올로",
      teamLogo: "/teams/sassuolo.png",
      assists: 6,
      gamesPlayed: 35,
    },
  ],
  bundesliga: [
    {
      id: 1,
      name: "플로리안 비르츠",
      team: "레버쿠젠",
      teamLogo: "/teams/leverkusen.png",
      assists: 12,
      gamesPlayed: 32,
    },
    { id: 2, name: "율리안 브란트", team: "도르트문트", teamLogo: "/teams/dortmund.png", assists: 10, gamesPlayed: 31 },
    { id: 3, name: "레로이 사네", team: "바이에른 뮌헨", teamLogo: "/teams/bayern.png", assists: 11, gamesPlayed: 29 },
    {
      id: 4,
      name: "제말 무시알라",
      team: "바이에른 뮌헨",
      teamLogo: "/teams/bayern.png",
      assists: 10,
      gamesPlayed: 33,
    },
    { id: 5, name: "그리말도", team: "레버쿠젠", teamLogo: "/teams/leverkusen.png", assists: 9, gamesPlayed: 31 },
    { id: 6, name: "크리스 퓔리히", team: "레버쿠젠", teamLogo: "/teams/leverkusen.png", assists: 9, gamesPlayed: 32 },
    { id: 7, name: "마르코 로이스", team: "도르트문트", teamLogo: "/teams/dortmund.png", assists: 8, gamesPlayed: 31 },
    {
      id: 8,
      name: "데니즈 운다브",
      team: "슈투트가르트",
      teamLogo: "/teams/stuttgart.png",
      assists: 8,
      gamesPlayed: 30,
    },
    { id: 9, name: "크리스 퓔리히", team: "레버쿠젠", teamLogo: "/teams/leverkusen.png", assists: 8, gamesPlayed: 32 },
    {
      id: 10,
      name: "요나스 호프만",
      team: "묀헨글라트바흐",
      teamLogo: "/teams/gladbach.png",
      assists: 7,
      gamesPlayed: 32,
    },
  ],
  "ligue-1": [
    { id: 1, name: "우사만 뎀벨레", team: "PSG", teamLogo: "/teams/psg.png", assists: 11, gamesPlayed: 28 },
    { id: 2, name: "브래들리 바르콜라", team: "리옹", teamLogo: "/teams/lyon.png", assists: 10, gamesPlayed: 33 },
    { id: 3, name: "킬리안 음바페", team: "PSG", teamLogo: "/teams/psg.png", assists: 8, gamesPlayed: 29 },
    { id: 4, name: "테지 사바니에", team: "몽펠리에", teamLogo: "/teams/montpellier.png", assists: 7, gamesPlayed: 33 },
    { id: 5, name: "아민 구이리", team: "랑스", teamLogo: "/teams/reims.png", assists: 7, gamesPlayed: 34 },
    { id: 6, name: "마테오 게두자이", team: "릴", teamLogo: "/teams/lille.png", assists: 7, gamesPlayed: 33 },
    { id: 7, name: "아슈라프 하키미", team: "PSG", teamLogo: "/teams/psg.png", assists: 6, gamesPlayed: 27 },
    {
      id: 8,
      name: "피에르-에메릭 오바메양",
      team: "마르세유",
      teamLogo: "/teams/marseille.png",
      assists: 6,
      gamesPlayed: 31,
    },
    { id: 9, name: "조나단 클라우스", team: "모나코", teamLogo: "/teams/monaco.png", assists: 6, gamesPlayed: 33 },
    { id: 10, name: "로망 델 카스티요", team: "브레스트", teamLogo: "/teams/brest.png", assists: 6, gamesPlayed: 33 },
  ],
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const league = searchParams.get("league")

  if (!league || !mockData[league as keyof typeof mockData]) {
    return NextResponse.json({ error: "유효하지 않은 리그 ID입니다." }, { status: 400 })
  }

  return NextResponse.json(mockData[league as keyof typeof mockData])
}
