import { NextResponse } from "next/server"

// 목업 데이터
const mockData = {
  "premier-league": [
    {
      id: 1,
      name: "엘링 홀란드",
      team: "맨체스터 시티",
      teamLogo: "/teams/man-city.png",
      goals: 27,
      penalties: 5,
      gamesPlayed: 31,
    },
    { id: 2, name: "콜 파머", team: "첼시", teamLogo: "/teams/chelsea.png", goals: 22, penalties: 2, gamesPlayed: 35 },
    {
      id: 3,
      name: "알렉산더 이사크",
      team: "뉴캐슬",
      teamLogo: "/teams/newcastle.png",
      goals: 21,
      penalties: 1,
      gamesPlayed: 30,
    },
    {
      id: 4,
      name: "손흥민",
      team: "토트넘",
      teamLogo: "/teams/tottenham.png",
      goals: 17,
      penalties: 0,
      gamesPlayed: 35,
    },
    {
      id: 5,
      name: "필 포든",
      team: "맨체스터 시티",
      teamLogo: "/teams/man-city.png",
      goals: 17,
      penalties: 0,
      gamesPlayed: 35,
    },
    {
      id: 6,
      name: "모하메드 살라",
      team: "리버풀",
      teamLogo: "/teams/liverpool.png",
      goals: 17,
      penalties: 3,
      gamesPlayed: 32,
    },
    {
      id: 7,
      name: "올리 왓킨스",
      team: "아스톤 빌라",
      teamLogo: "/teams/aston-villa.png",
      goals: 19,
      penalties: 0,
      gamesPlayed: 37,
    },
    {
      id: 8,
      name: "에르네스토 은쿤쿠",
      team: "첼시",
      teamLogo: "/teams/chelsea.png",
      goals: 16,
      penalties: 0,
      gamesPlayed: 37,
    },
    {
      id: 9,
      name: "브라이언 음부에모",
      team: "브렌트포드",
      teamLogo: "/teams/brentford.png",
      goals: 16,
      penalties: 2,
      gamesPlayed: 33,
    },
    {
      id: 10,
      name: "자렐 콰나",
      team: "노팅엄 포레스트",
      teamLogo: "/teams/nottingham.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 37,
    },
  ],
  "la-liga": [
    {
      id: 1,
      name: "아를링 홀란드",
      team: "맨체스터 시티",
      teamLogo: "/teams/man-city.png",
      goals: 36,
      penalties: 7,
      gamesPlayed: 35,
    },
    {
      id: 2,
      name: "해리 케인",
      team: "바이에른 뮌헨",
      teamLogo: "/teams/bayern.png",
      goals: 36,
      penalties: 5,
      gamesPlayed: 32,
    },
    { id: 3, name: "킬리안 음바페", team: "PSG", teamLogo: "/teams/psg.png", goals: 27, penalties: 5, gamesPlayed: 29 },
    {
      id: 4,
      name: "빅터 오시멘",
      team: "나폴리",
      teamLogo: "/teams/napoli.png",
      goals: 26,
      penalties: 0,
      gamesPlayed: 32,
    },
    {
      id: 5,
      name: "로베르트 레반도프스키",
      team: "바르셀로나",
      teamLogo: "/teams/barcelona.png",
      goals: 24,
      penalties: 3,
      gamesPlayed: 34,
    },
    {
      id: 6,
      name: "라우타로 마르티네스",
      team: "인테르 밀란",
      teamLogo: "/teams/inter.png",
      goals: 24,
      penalties: 2,
      gamesPlayed: 33,
    },
    {
      id: 7,
      name: "세르주 귀라시",
      team: "슈투트가르트",
      teamLogo: "/teams/stuttgart.png",
      goals: 24,
      penalties: 0,
      gamesPlayed: 30,
    },
    {
      id: 8,
      name: "알렉산더 소를로스",
      team: "지로나",
      teamLogo: "/teams/girona.png",
      goals: 21,
      penalties: 0,
      gamesPlayed: 35,
    },
    {
      id: 9,
      name: "알바로 모라타",
      team: "아틀레티코 마드리드",
      teamLogo: "/teams/atletico-madrid.png",
      goals: 21,
      penalties: 0,
      gamesPlayed: 36,
    },
    {
      id: 10,
      name: "비니시우스 주니오르",
      team: "레알 마드리드",
      teamLogo: "/teams/real-madrid.png",
      goals: 20,
      penalties: 2,
      gamesPlayed: 26,
    },
  ],
  "serie-a": [
    {
      id: 1,
      name: "라우타로 마르티네스",
      team: "인테르 밀란",
      teamLogo: "/teams/inter.png",
      goals: 24,
      penalties: 2,
      gamesPlayed: 33,
    },
    {
      id: 2,
      name: "두산 블라호비치",
      team: "유벤투스",
      teamLogo: "/teams/juventus.png",
      goals: 16,
      penalties: 4,
      gamesPlayed: 32,
    },
    {
      id: 3,
      name: "마테오 레타구이",
      team: "볼로냐",
      teamLogo: "/teams/bologna.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 35,
    },
    {
      id: 4,
      name: "올리비에 지루",
      team: "AC 밀란",
      teamLogo: "/teams/milan.png",
      goals: 14,
      penalties: 0,
      gamesPlayed: 33,
    },
    {
      id: 5,
      name: "마르코스 튀람",
      team: "인테르 밀란",
      teamLogo: "/teams/inter.png",
      goals: 13,
      penalties: 0,
      gamesPlayed: 33,
    },
    {
      id: 6,
      name: "빅터 오시멘",
      team: "나폴리",
      teamLogo: "/teams/napoli.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 25,
    },
    {
      id: 7,
      name: "마테오 폴리타노",
      team: "나폴리",
      teamLogo: "/teams/napoli.png",
      goals: 10,
      penalties: 1,
      gamesPlayed: 35,
    },
    {
      id: 8,
      name: "파울로 디발라",
      team: "로마",
      teamLogo: "/teams/roma.png",
      goals: 12,
      penalties: 3,
      gamesPlayed: 28,
    },
    {
      id: 9,
      name: "로멜루 루카쿠",
      team: "로마",
      teamLogo: "/teams/roma.png",
      goals: 12,
      penalties: 1,
      gamesPlayed: 32,
    },
    {
      id: 10,
      name: "안드레아 피나몬티",
      team: "사수올로",
      teamLogo: "/teams/sassuolo.png",
      goals: 11,
      penalties: 2,
      gamesPlayed: 35,
    },
  ],
  bundesliga: [
    {
      id: 1,
      name: "해리 케인",
      team: "바이에른 뮌헨",
      teamLogo: "/teams/bayern.png",
      goals: 36,
      penalties: 5,
      gamesPlayed: 32,
    },
    {
      id: 2,
      name: "세르주 귀라시",
      team: "슈투트가르트",
      teamLogo: "/teams/stuttgart.png",
      goals: 24,
      penalties: 0,
      gamesPlayed: 30,
    },
    {
      id: 3,
      name: "로이스 오페",
      team: "유니온 베를린",
      teamLogo: "/teams/union-berlin.png",
      goals: 17,
      penalties: 0,
      gamesPlayed: 31,
    },
    {
      id: 4,
      name: "빅터 보니페이스",
      team: "레버쿠젠",
      teamLogo: "/teams/leverkusen.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 32,
    },
    {
      id: 5,
      name: "데니즈 운다브",
      team: "슈투트가르트",
      teamLogo: "/teams/stuttgart.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 30,
    },
    {
      id: 6,
      name: "니클라스 퓔크루그",
      team: "도르트문트",
      teamLogo: "/teams/dortmund.png",
      goals: 14,
      penalties: 1,
      gamesPlayed: 28,
    },
    {
      id: 7,
      name: "로베르트 안드리히",
      team: "레버쿠젠",
      teamLogo: "/teams/leverkusen.png",
      goals: 14,
      penalties: 5,
      gamesPlayed: 31,
    },
    {
      id: 8,
      name: "티모 베르너",
      team: "라이프치히",
      teamLogo: "/teams/leipzig.png",
      goals: 12,
      penalties: 0,
      gamesPlayed: 27,
    },
    {
      id: 9,
      name: "요나스 빈드",
      team: "볼프스부르크",
      teamLogo: "/teams/wolfsburg.png",
      goals: 12,
      penalties: 0,
      gamesPlayed: 33,
    },
    {
      id: 10,
      name: "마르빈 두크슈",
      team: "도르트문트",
      teamLogo: "/teams/dortmund.png",
      goals: 12,
      penalties: 0,
      gamesPlayed: 29,
    },
  ],
  "ligue-1": [
    { id: 1, name: "킬리안 음바페", team: "PSG", teamLogo: "/teams/psg.png", goals: 27, penalties: 5, gamesPlayed: 29 },
    {
      id: 2,
      name: "조나단 데이비드",
      team: "릴",
      teamLogo: "/teams/lille.png",
      goals: 19,
      penalties: 4,
      gamesPlayed: 34,
    },
    {
      id: 3,
      name: "알렉산드르 라카제트",
      team: "리옹",
      teamLogo: "/teams/lyon.png",
      goals: 19,
      penalties: 5,
      gamesPlayed: 32,
    },
    {
      id: 4,
      name: "와히 카즈리",
      team: "몽펠리에",
      teamLogo: "/teams/montpellier.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 30,
    },
    {
      id: 5,
      name: "아민 구이리",
      team: "랑스",
      teamLogo: "/teams/reims.png",
      goals: 17,
      penalties: 0,
      gamesPlayed: 34,
    },
    {
      id: 6,
      name: "피에르-에메릭 오바메양",
      team: "마르세유",
      teamLogo: "/teams/marseille.png",
      goals: 16,
      penalties: 0,
      gamesPlayed: 31,
    },
    {
      id: 7,
      name: "랜달 콜로 무아니",
      team: "PSG",
      teamLogo: "/teams/psg.png",
      goals: 15,
      penalties: 0,
      gamesPlayed: 33,
    },
    {
      id: 8,
      name: "테지 사바니에",
      team: "몽펠리에",
      teamLogo: "/teams/montpellier.png",
      goals: 14,
      penalties: 0,
      gamesPlayed: 33,
    },
    {
      id: 9,
      name: "브래들리 바르콜라",
      team: "리옹",
      teamLogo: "/teams/lyon.png",
      goals: 13,
      penalties: 0,
      gamesPlayed: 33,
    },
    {
      id: 10,
      name: "모하메드 바요",
      team: "클레르몽",
      teamLogo: "/teams/clermont.png",
      goals: 12,
      penalties: 0,
      gamesPlayed: 33,
    },
  ],
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const league = searchParams.get("league")

  if (!league || !mockData[league as keyof typeof mockData]) {
    return NextResponse.json({ error: "유효하지 않은 리그 ID입니다." }, { status: 400 })
  }

  return NextResponse.json(mockData[league as keyof typeof mockData])
}
