import { NextResponse } from "next/server";

// 목업 데이터
const mockData = {
  "premier-league": [
    {
      id: 1,
      position: 1,
      name: "맨체스터 시티",
      logo: "/teams/man-city.png",
      played: 38,
      points: 91,
      won: 29,
      drawn: 4,
      lost: 5,
      goalsFor: 94,
      goalsAgainst: 32,
      goalDifference: 62,
    },
    {
      id: 2,
      position: 2,
      name: "아스널",
      logo: "/teams/arsenal.png",
      played: 38,
      points: 89,
      won: 28,
      drawn: 5,
      lost: 5,
      goalsFor: 91,
      goalsAgainst: 29,
      goalDifference: 62,
    },
    {
      id: 3,
      position: 3,
      name: "리버풀",
      logo: "/teams/liverpool.png",
      played: 38,
      points: 82,
      won: 24,
      drawn: 10,
      lost: 4,
      goalsFor: 86,
      goalsAgainst: 41,
      goalDifference: 45,
    },
    {
      id: 4,
      position: 4,
      name: "아스톤 빌라",
      logo: "/teams/aston-villa.png",
      played: 38,
      points: 68,
      won: 20,
      drawn: 8,
      lost: 10,
      goalsFor: 76,
      goalsAgainst: 58,
      goalDifference: 18,
    },
    {
      id: 5,
      position: 5,
      name: "토트넘",
      logo: "/teams/tottenham.png",
      played: 38,
      points: 66,
      won: 20,
      drawn: 6,
      lost: 12,
      goalsFor: 74,
      goalsAgainst: 61,
      goalDifference: 13,
    },
    {
      id: 6,
      position: 6,
      name: "맨체스터 유나이티드",
      logo: "/teams/man-utd.png",
      played: 38,
      points: 60,
      won: 18,
      drawn: 6,
      lost: 14,
      goalsFor: 57,
      goalsAgainst: 58,
      goalDifference: -1,
    },
    {
      id: 7,
      position: 7,
      name: "뉴캐슬",
      logo: "/teams/newcastle.png",
      played: 38,
      points: 60,
      won: 17,
      drawn: 9,
      lost: 12,
      goalsFor: 85,
      goalsAgainst: 56,
      goalDifference: 29,
    },
    {
      id: 8,
      position: 8,
      name: "첼시",
      logo: "/teams/chelsea.png",
      played: 38,
      points: 57,
      won: 16,
      drawn: 9,
      lost: 13,
      goalsFor: 77,
      goalsAgainst: 63,
      goalDifference: 14,
    },
    {
      id: 9,
      position: 9,
      name: "웨스트햄",
      logo: "/teams/west-ham.png",
      played: 38,
      points: 52,
      won: 15,
      drawn: 7,
      lost: 16,
      goalsFor: 59,
      goalsAgainst: 69,
      goalDifference: -10,
    },
    {
      id: 10,
      position: 10,
      name: "브라이튼",
      logo: "/teams/brighton.png",
      played: 38,
      points: 48,
      won: 12,
      drawn: 12,
      lost: 14,
      goalsFor: 53,
      goalsAgainst: 53,
      goalDifference: 0,
    },
    {
      id: 11,
      position: 11,
      name: "울버햄튼",
      logo: "/teams/wolves.png",
      played: 38,
      points: 46,
      won: 13,
      drawn: 7,
      lost: 18,
      goalsFor: 49,
      goalsAgainst: 60,
      goalDifference: -11,
    },
    {
      id: 12,
      position: 12,
      name: "크리스탈 팰리스",
      logo: "/teams/crystal-palace.png",
      played: 38,
      points: 44,
      won: 11,
      drawn: 11,
      lost: 16,
      goalsFor: 47,
      goalsAgainst: 58,
      goalDifference: -11,
    },
    {
      id: 13,
      position: 13,
      name: "풀럼",
      logo: "/teams/fulham.png",
      played: 38,
      points: 43,
      won: 12,
      drawn: 7,
      lost: 19,
      goalsFor: 51,
      goalsAgainst: 68,
      goalDifference: -17,
    },
    {
      id: 14,
      position: 14,
      name: "브렌트포드",
      logo: "/teams/brentford.png",
      played: 38,
      points: 42,
      won: 11,
      drawn: 9,
      lost: 18,
      goalsFor: 54,
      goalsAgainst: 60,
      goalDifference: -6,
    },
    {
      id: 15,
      position: 15,
      name: "본머스",
      logo: "/teams/bournemouth.png",
      played: 38,
      points: 42,
      won: 11,
      drawn: 9,
      lost: 18,
      goalsFor: 46,
      goalsAgainst: 71,
      goalDifference: -25,
    },
    {
      id: 16,
      position: 16,
      name: "에버턴",
      logo: "/teams/everton.png",
      played: 38,
      points: 40,
      won: 13,
      drawn: 7,
      lost: 18,
      goalsFor: 40,
      goalsAgainst: 52,
      goalDifference: -12,
    },
    {
      id: 17,
      position: 17,
      name: "노팅엄 포레스트",
      logo: "/teams/nottingham.png",
      played: 38,
      points: 31,
      won: 8,
      drawn: 10,
      lost: 20,
      goalsFor: 44,
      goalsAgainst: 68,
      goalDifference: -24,
    },
    {
      id: 18,
      position: 18,
      name: "루턴 타운",
      logo: "/teams/luton.png",
      played: 38,
      points: 26,
      won: 6,
      drawn: 8,
      lost: 24,
      goalsFor: 49,
      goalsAgainst: 79,
      goalDifference: -30,
    },
    {
      id: 19,
      position: 19,
      name: "번리",
      logo: "/teams/burnley.png",
      played: 38,
      points: 24,
      won: 5,
      drawn: 9,
      lost: 24,
      goalsFor: 39,
      goalsAgainst: 79,
      goalDifference: -40,
    },
    {
      id: 20,
      position: 20,
      name: "셰필드 유나이티드",
      logo: "/teams/sheffield.png",
      played: 38,
      points: 16,
      won: 3,
      drawn: 7,
      lost: 28,
      goalsFor: 35,
      goalsAgainst: 104,
      goalDifference: -69,
    },
  ],
  "la-liga": [
    {
      id: 1,
      position: 1,
      name: "레알 마드리드",
      logo: "/teams/real-madrid.png",
      played: 38,
      points: 95,
      won: 30,
      drawn: 5,
      lost: 3,
      goalsFor: 86,
      goalsAgainst: 25,
      goalDifference: 61,
    },
    {
      id: 2,
      position: 2,
      name: "바르셀로나",
      logo: "/teams/barcelona.png",
      played: 38,
      points: 85,
      won: 26,
      drawn: 7,
      lost: 5,
      goalsFor: 71,
      goalsAgainst: 40,
      goalDifference: 31,
    },
    {
      id: 3,
      position: 3,
      name: "지로나",
      logo: "/teams/girona.png",
      played: 38,
      points: 78,
      won: 23,
      drawn: 9,
      lost: 6,
      goalsFor: 82,
      goalsAgainst: 52,
      goalDifference: 30,
    },
    {
      id: 4,
      position: 4,
      name: "아틀레티코 마드리드",
      logo: "/teams/atletico-madrid.png",
      played: 38,
      points: 73,
      won: 22,
      drawn: 7,
      lost: 9,
      goalsFor: 71,
      goalsAgainst: 44,
      goalDifference: 27,
    },
    {
      id: 5,
      position: 5,
      name: "아틀레틱 빌바오",
      logo: "/teams/athletic-bilbao.png",
      played: 38,
      points: 68,
      won: 19,
      drawn: 11,
      lost: 8,
      goalsFor: 59,
      goalsAgainst: 39,
      goalDifference: 20,
    },
    {
      id: 6,
      position: 6,
      name: "레알 소시에다드",
      logo: "/teams/real-sociedad.png",
      played: 38,
      points: 60,
      won: 16,
      drawn: 12,
      lost: 10,
      goalsFor: 47,
      goalsAgainst: 38,
      goalDifference: 9,
    },
    {
      id: 7,
      position: 7,
      name: "레알 베티스",
      logo: "/teams/real-betis.png",
      played: 38,
      points: 57,
      won: 14,
      drawn: 15,
      lost: 9,
      goalsFor: 48,
      goalsAgainst: 45,
      goalDifference: 3,
    },
    {
      id: 8,
      position: 8,
      name: "비야레알",
      logo: "/teams/villarreal.png",
      played: 38,
      points: 53,
      won: 15,
      drawn: 8,
      lost: 15,
      goalsFor: 60,
      goalsAgainst: 59,
      goalDifference: 1,
    },
    {
      id: 9,
      position: 9,
      name: "발렌시아",
      logo: "/teams/valencia.png",
      played: 38,
      points: 51,
      won: 14,
      drawn: 9,
      lost: 15,
      goalsFor: 43,
      goalsAgainst: 45,
      goalDifference: -2,
    },
    {
      id: 10,
      position: 10,
      name: "오사수나",
      logo: "/teams/osasuna.png",
      played: 38,
      points: 48,
      won: 13,
      drawn: 9,
      lost: 16,
      goalsFor: 42,
      goalsAgainst: 51,
      goalDifference: -9,
    },
    {
      id: 11,
      position: 11,
      name: "세비야",
      logo: "/teams/sevilla.png",
      played: 38,
      points: 44,
      won: 11,
      drawn: 11,
      lost: 16,
      goalsFor: 46,
      goalsAgainst: 53,
      goalDifference: -7,
    },
    {
      id: 12,
      position: 12,
      name: "라스 팔마스",
      logo: "/teams/las-palmas.png",
      played: 38,
      points: 41,
      won: 11,
      drawn: 8,
      lost: 19,
      goalsFor: 36,
      goalsAgainst: 54,
      goalDifference: -18,
    },
    {
      id: 13,
      position: 13,
      name: "마요르카",
      logo: "/teams/mallorca.png",
      played: 38,
      points: 40,
      won: 9,
      drawn: 13,
      lost: 16,
      goalsFor: 34,
      goalsAgainst: 46,
      goalDifference: -12,
    },
    {
      id: 14,
      position: 14,
      name: "알라베스",
      logo: "/teams/alaves.png",
      played: 38,
      points: 39,
      won: 10,
      drawn: 9,
      lost: 19,
      goalsFor: 35,
      goalsAgainst: 52,
      goalDifference: -17,
    },
    {
      id: 15,
      position: 15,
      name: "라요 바예카노",
      logo: "/teams/rayo-vallecano.png",
      played: 38,
      points: 38,
      won: 9,
      drawn: 11,
      lost: 18,
      goalsFor: 36,
      goalsAgainst: 56,
      goalDifference: -20,
    },
    {
      id: 16,
      position: 16,
      name: "셀타 비고",
      logo: "/teams/celta-vigo.png",
      played: 38,
      points: 37,
      won: 9,
      drawn: 10,
      lost: 19,
      goalsFor: 43,
      goalsAgainst: 61,
      goalDifference: -18,
    },
    {
      id: 17,
      position: 17,
      name: "헤타페",
      logo: "/teams/getafe.png",
      played: 38,
      points: 37,
      won: 8,
      drawn: 13,
      lost: 17,
      goalsFor: 37,
      goalsAgainst: 53,
      goalDifference: -16,
    },
    {
      id: 18,
      position: 18,
      name: "카디스",
      logo: "/teams/cadiz.png",
      played: 38,
      points: 34,
      won: 6,
      drawn: 16,
      lost: 16,
      goalsFor: 28,
      goalsAgainst: 54,
      goalDifference: -26,
    },
    {
      id: 19,
      position: 19,
      name: "그라나다",
      logo: "/teams/granada.png",
      played: 38,
      points: 25,
      won: 5,
      drawn: 10,
      lost: 23,
      goalsFor: 36,
      goalsAgainst: 71,
      goalDifference: -35,
    },
    {
      id: 20,
      position: 20,
      name: "알메리아",
      logo: "/teams/almeria.png",
      played: 38,
      points: 17,
      won: 2,
      drawn: 11,
      lost: 25,
      goalsFor: 35,
      goalsAgainst: 77,
      goalDifference: -42,
    },
  ],
  "serie-a": [
    {
      id: 1,
      position: 1,
      name: "인테르 밀란",
      logo: "/teams/inter.png",
      played: 38,
      points: 94,
      won: 30,
      drawn: 4,
      lost: 4,
      goalsFor: 89,
      goalsAgainst: 22,
      goalDifference: 67,
    },
    {
      id: 2,
      position: 2,
      name: "AC 밀란",
      logo: "/teams/milan.png",
      played: 38,
      points: 75,
      won: 22,
      drawn: 9,
      lost: 7,
      goalsFor: 71,
      goalsAgainst: 49,
      goalDifference: 22,
    },
    {
      id: 3,
      position: 3,
      name: "유벤투스",
      logo: "/teams/juventus.png",
      played: 38,
      points: 71,
      won: 20,
      drawn: 11,
      lost: 7,
      goalsFor: 54,
      goalsAgainst: 31,
      goalDifference: 23,
    },
    {
      id: 4,
      position: 4,
      name: "아탈란타",
      logo: "/teams/atalanta.png",
      played: 38,
      points: 69,
      won: 20,
      drawn: 9,
      lost: 9,
      goalsFor: 70,
      goalsAgainst: 40,
      goalDifference: 30,
    },
    {
      id: 5,
      position: 5,
      name: "볼로냐",
      logo: "/teams/bologna.png",
      played: 38,
      points: 68,
      won: 18,
      drawn: 14,
      lost: 6,
      goalsFor: 54,
      goalsAgainst: 33,
      goalDifference: 21,
    },
    {
      id: 6,
      position: 6,
      name: "로마",
      logo: "/teams/roma.png",
      played: 38,
      points: 63,
      won: 17,
      drawn: 12,
      lost: 9,
      goalsFor: 67,
      goalsAgainst: 47,
      goalDifference: 20,
    },
    {
      id: 7,
      position: 7,
      name: "라치오",
      logo: "/teams/lazio.png",
      played: 38,
      points: 60,
      won: 18,
      drawn: 6,
      lost: 14,
      goalsFor: 51,
      goalsAgainst: 40,
      goalDifference: 11,
    },
    {
      id: 8,
      position: 8,
      name: "피오렌티나",
      logo: "/teams/fiorentina.png",
      played: 38,
      points: 57,
      won: 16,
      drawn: 9,
      lost: 13,
      goalsFor: 54,
      goalsAgainst: 42,
      goalDifference: 12,
    },
    {
      id: 9,
      position: 9,
      name: "나폴리",
      logo: "/teams/napoli.png",
      played: 38,
      points: 52,
      won: 14,
      drawn: 10,
      lost: 14,
      goalsFor: 55,
      goalsAgainst: 48,
      goalDifference: 7,
    },
    {
      id: 10,
      position: 10,
      name: "토리노",
      logo: "/teams/torino.png",
      played: 38,
      points: 52,
      won: 13,
      drawn: 13,
      lost: 12,
      goalsFor: 36,
      goalsAgainst: 36,
      goalDifference: 0,
    },
    {
      id: 11,
      position: 11,
      name: "제노아",
      logo: "/teams/genoa.png",
      played: 38,
      points: 49,
      won: 12,
      drawn: 13,
      lost: 13,
      goalsFor: 43,
      goalsAgainst: 45,
      goalDifference: -2,
    },
    {
      id: 12,
      position: 12,
      name: "몬자",
      logo: "/teams/monza.png",
      played: 38,
      points: 45,
      won: 11,
      drawn: 12,
      lost: 15,
      goalsFor: 37,
      goalsAgainst: 48,
      goalDifference: -11,
    },
    {
      id: 13,
      position: 13,
      name: "레체",
      logo: "/teams/lecce.png",
      played: 38,
      points: 40,
      won: 8,
      drawn: 16,
      lost: 14,
      goalsFor: 33,
      goalsAgainst: 50,
      goalDifference: -17,
    },
    {
      id: 14,
      position: 14,
      name: "우디네세",
      logo: "/teams/udinese.png",
      played: 38,
      points: 37,
      won: 7,
      drawn: 16,
      lost: 15,
      goalsFor: 36,
      goalsAgainst: 56,
      goalDifference: -20,
    },
    {
      id: 15,
      position: 15,
      name: "칼리아리",
      logo: "/teams/cagliari.png",
      played: 38,
      points: 36,
      won: 8,
      drawn: 12,
      lost: 18,
      goalsFor: 40,
      goalsAgainst: 64,
      goalDifference: -24,
    },
    {
      id: 16,
      position: 16,
      name: "베로나",
      logo: "/teams/verona.png",
      played: 38,
      points: 35,
      won: 9,
      drawn: 8,
      lost: 21,
      goalsFor: 37,
      goalsAgainst: 55,
      goalDifference: -18,
    },
    {
      id: 17,
      position: 17,
      name: "엠폴리",
      logo: "/teams/empoli.png",
      played: 38,
      points: 33,
      won: 8,
      drawn: 9,
      lost: 21,
      goalsFor: 26,
      goalsAgainst: 55,
      goalDifference: -29,
    },
    {
      id: 18,
      position: 18,
      name: "프로시노네",
      logo: "/teams/frosinone.png",
      played: 38,
      points: 32,
      won: 7,
      drawn: 11,
      lost: 20,
      goalsFor: 42,
      goalsAgainst: 71,
      goalDifference: -29,
    },
    {
      id: 19,
      position: 19,
      name: "사수올로",
      logo: "/teams/sassuolo.png",
      played: 38,
      points: 29,
      won: 7,
      drawn: 8,
      lost: 23,
      goalsFor: 37,
      goalsAgainst: 72,
      goalDifference: -35,
    },
    {
      id: 20,
      position: 20,
      name: "살레르니타나",
      logo: "/teams/salernitana.png",
      played: 38,
      points: 17,
      won: 2,
      drawn: 11,
      lost: 25,
      goalsFor: 30,
      goalsAgainst: 77,
      goalDifference: -47,
    },
  ],
  bundesliga: [
    {
      id: 1,
      position: 1,
      name: "바이어 레버쿠젠",
      logo: "/teams/leverkusen.png",
      played: 34,
      points: 90,
      won: 28,
      drawn: 6,
      lost: 0,
      goalsFor: 89,
      goalsAgainst: 24,
      goalDifference: 65,
    },
    {
      id: 2,
      position: 2,
      name: "바이에른 뮌헨",
      logo: "/teams/bayern.png",
      played: 34,
      points: 79,
      won: 25,
      drawn: 4,
      lost: 5,
      goalsFor: 94,
      goalsAgainst: 40,
      goalDifference: 54,
    },
    {
      id: 3,
      position: 3,
      name: "슈투트가르트",
      logo: "/teams/stuttgart.png",
      played: 34,
      points: 73,
      won: 23,
      drawn: 4,
      lost: 7,
      goalsFor: 76,
      goalsAgainst: 41,
      goalDifference: 35,
    },
    {
      id: 4,
      position: 4,
      name: "RB 라이프치히",
      logo: "/teams/leipzig.png",
      played: 34,
      points: 66,
      won: 20,
      drawn: 6,
      lost: 8,
      goalsFor: 73,
      goalsAgainst: 34,
      goalDifference: 39,
    },
    {
      id: 5,
      position: 5,
      name: "도르트문트",
      logo: "/teams/dortmund.png",
      played: 34,
      points: 63,
      won: 19,
      drawn: 6,
      lost: 9,
      goalsFor: 63,
      goalsAgainst: 44,
      goalDifference: 19,
    },
    {
      id: 6,
      position: 6,
      name: "프랑크푸르트",
      logo: "/teams/frankfurt.png",
      played: 34,
      points: 47,
      won: 11,
      drawn: 14,
      lost: 9,
      goalsFor: 52,
      goalsAgainst: 51,
      goalDifference: 1,
    },
    {
      id: 7,
      position: 7,
      name: "호펜하임",
      logo: "/teams/hoffenheim.png",
      played: 34,
      points: 46,
      won: 13,
      drawn: 7,
      lost: 14,
      goalsFor: 63,
      goalsAgainst: 67,
      goalDifference: -4,
    },
    {
      id: 8,
      position: 8,
      name: "브레멘",
      logo: "/teams/bremen.png",
      played: 34,
      points: 45,
      won: 12,
      drawn: 9,
      lost: 13,
      goalsFor: 50,
      goalsAgainst: 55,
      goalDifference: -5,
    },
    {
      id: 9,
      position: 9,
      name: "프라이부르크",
      logo: "/teams/freiburg.png",
      played: 34,
      points: 44,
      won: 12,
      drawn: 8,
      lost: 14,
      goalsFor: 47,
      goalsAgainst: 56,
      goalDifference: -9,
    },
    {
      id: 10,
      position: 10,
      name: "헤르타 베를린",
      logo: "/teams/hertha.png",
      played: 34,
      points: 40,
      won: 10,
      drawn: 10,
      lost: 14,
      goalsFor: 47,
      goalsAgainst: 55,
      goalDifference: -8,
    },
    {
      id: 11,
      position: 11,
      name: "하이덴하임",
      logo: "/teams/heidenheim.png",
      played: 34,
      points: 39,
      won: 10,
      drawn: 9,
      lost: 15,
      goalsFor: 47,
      goalsAgainst: 55,
      goalDifference: -8,
    },
    {
      id: 12,
      position: 12,
      name: "보훔",
      logo: "/teams/bochum.png",
      played: 34,
      points: 36,
      won: 9,
      drawn: 9,
      lost: 16,
      goalsFor: 42,
      goalsAgainst: 68,
      goalDifference: -26,
    },
    {
      id: 13,
      position: 13,
      name: "묀헨글라트바흐",
      logo: "/teams/gladbach.png",
      played: 34,
      points: 34,
      won: 8,
      drawn: 10,
      lost: 16,
      goalsFor: 58,
      goalsAgainst: 67,
      goalDifference: -9,
    },
    {
      id: 14,
      position: 14,
      name: "유니온 베를린",
      logo: "/teams/union-berlin.png",
      played: 34,
      points: 33,
      won: 9,
      drawn: 6,
      lost: 19,
      goalsFor: 35,
      goalsAgainst: 60,
      goalDifference: -25,
    },
    {
      id: 15,
      position: 15,
      name: "마인츠",
      logo: "/teams/mainz.png",
      played: 34,
      points: 31,
      won: 6,
      drawn: 13,
      lost: 15,
      goalsFor: 36,
      goalsAgainst: 55,
      goalDifference: -19,
    },
    {
      id: 16,
      position: 16,
      name: "쾰른",
      logo: "/teams/koln.png",
      played: 34,
      points: 27,
      won: 5,
      drawn: 12,
      lost: 17,
      goalsFor: 29,
      goalsAgainst: 60,
      goalDifference: -31,
    },
    {
      id: 17,
      position: 17,
      name: "볼프스부르크",
      logo: "/teams/wolfsburg.png",
      played: 34,
      points: 25,
      won: 6,
      drawn: 7,
      lost: 21,
      goalsFor: 35,
      goalsAgainst: 65,
      goalDifference: -30,
    },
    {
      id: 18,
      position: 18,
      name: "다름슈타트",
      logo: "/teams/darmstadt.png",
      played: 34,
      points: 17,
      won: 3,
      drawn: 8,
      lost: 23,
      goalsFor: 30,
      goalsAgainst: 84,
      goalDifference: -54,
    },
  ],
  "ligue-1": [
    {
      id: 1,
      position: 1,
      name: "PSG",
      logo: "/teams/psg.png",
      played: 34,
      points: 79,
      won: 23,
      drawn: 10,
      lost: 1,
      goalsFor: 85,
      goalsAgainst: 29,
      goalDifference: 56,
    },
    {
      id: 2,
      position: 2,
      name: "모나코",
      logo: "/teams/monaco.png",
      played: 34,
      points: 67,
      won: 19,
      drawn: 10,
      lost: 5,
      goalsFor: 65,
      goalsAgainst: 42,
      goalDifference: 23,
    },
    {
      id: 3,
      position: 3,
      name: "브레스트",
      logo: "/teams/brest.png",
      played: 34,
      points: 61,
      won: 17,
      drawn: 10,
      lost: 7,
      goalsFor: 54,
      goalsAgainst: 34,
      goalDifference: 20,
    },
    {
      id: 4,
      position: 4,
      name: "릴",
      logo: "/teams/lille.png",
      played: 34,
      points: 59,
      won: 16,
      drawn: 11,
      lost: 7,
      goalsFor: 47,
      goalsAgainst: 30,
      goalDifference: 17,
    },
    {
      id: 5,
      position: 5,
      name: "니스",
      logo: "/teams/nice.png",
      played: 34,
      points: 58,
      won: 16,
      drawn: 10,
      lost: 8,
      goalsFor: 42,
      goalsAgainst: 29,
      goalDifference: 13,
    },
    {
      id: 6,
      position: 6,
      name: "랑스",
      logo: "/teams/reims.png",
      played: 34,
      points: 50,
      won: 13,
      drawn: 11,
      lost: 10,
      goalsFor: 47,
      goalsAgainst: 42,
      goalDifference: 5,
    },
    {
      id: 7,
      position: 7,
      name: "리옹",
      logo: "/teams/lyon.png",
      played: 34,
      points: 50,
      won: 14,
      drawn: 8,
      lost: 12,
      goalsFor: 53,
      goalsAgainst: 51,
      goalDifference: 2,
    },
    {
      id: 8,
      position: 8,
      name: "마르세유",
      logo: "/teams/marseille.png",
      played: 34,
      points: 47,
      won: 11,
      drawn: 14,
      lost: 9,
      goalsFor: 52,
      goalsAgainst: 41,
      goalDifference: 11,
    },
    {
      id: 9,
      position: 9,
      name: "랑",
      logo: "/teams/lens.png",
      played: 34,
      points: 46,
      won: 12,
      drawn: 10,
      lost: 12,
      goalsFor: 41,
      goalsAgainst: 40,
      goalDifference: 1,
    },
    {
      id: 10,
      position: 10,
      name: "툴루즈",
      logo: "/teams/toulouse.png",
      played: 34,
      points: 40,
      won: 10,
      drawn: 10,
      lost: 14,
      goalsFor: 41,
      goalsAgainst: 48,
      goalDifference: -7,
    },
    {
      id: 11,
      position: 11,
      name: "렌",
      logo: "/teams/rennes.png",
      played: 34,
      points: 39,
      won: 10,
      drawn: 9,
      lost: 15,
      goalsFor: 48,
      goalsAgainst: 50,
      goalDifference: -2,
    },
    {
      id: 12,
      position: 12,
      name: "몽펠리에",
      logo: "/teams/montpellier.png",
      played: 34,
      points: 37,
      won: 9,
      drawn: 10,
      lost: 15,
      goalsFor: 40,
      goalsAgainst: 50,
      goalDifference: -10,
    },
    {
      id: 13,
      position: 13,
      name: "스트라스부르",
      logo: "/teams/strasbourg.png",
      played: 34,
      points: 36,
      won: 9,
      drawn: 9,
      lost: 16,
      goalsFor: 37,
      goalsAgainst: 54,
      goalDifference: -17,
    },
    {
      id: 14,
      position: 14,
      name: "낭트",
      logo: "/teams/nantes.png",
      played: 34,
      points: 33,
      won: 9,
      drawn: 6,
      lost: 19,
      goalsFor: 32,
      goalsAgainst: 54,
      goalDifference: -22,
    },
    {
      id: 15,
      position: 15,
      name: "메스",
      logo: "/teams/metz.png",
      played: 34,
      points: 32,
      won: 8,
      drawn: 8,
      lost: 18,
      goalsFor: 34,
      goalsAgainst: 54,
      goalDifference: -20,
    },
    {
      id: 16,
      position: 16,
      name: "르아브르",
      logo: "/teams/le-havre.png",
      played: 34,
      points: 32,
      won: 7,
      drawn: 11,
      lost: 16,
      goalsFor: 35,
      goalsAgainst: 48,
      goalDifference: -13,
    },
    {
      id: 17,
      position: 17,
      name: "로리앙",
      logo: "/teams/lorient.png",
      played: 34,
      points: 26,
      won: 6,
      drawn: 8,
      lost: 20,
      goalsFor: 36,
      goalsAgainst: 67,
      goalDifference: -31,
    },
    {
      id: 18,
      position: 18,
      name: "클레르몽",
      logo: "/teams/clermont.png",
      played: 34,
      points: 25,
      won: 5,
      drawn: 10,
      lost: 19,
      goalsFor: 29,
      goalsAgainst: 62,
      goalDifference: -33,
    },
  ],
};

// API-Football 형식 데이터 타입
type StandingsResponse = {
  response: Array<{
    team: {
      id: number;
      name: string;
      logo: string;
    };
    points: number;
    rank: number;
    all: {
      win: number;
      draw: number;
      lose: number;
      goals: {
        for: number;
        against: number;
      };
    };
  }>;
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const league = searchParams.get("league");
  const season = searchParams.get("season");

  if (league && season) {
    // API-Football 형식으로 요청이 온 경우
    try {
      // 여기서는 목업 데이터를 반환하지만 실제로는 API-Football API에 요청을 보낼 수 있습니다
      const mockApiFootballData: StandingsResponse = {
        response: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media.api-sports.io/football/teams/33.png",
            },
            points: 58,
            rank: 4,
            all: { win: 18, draw: 4, lose: 6, goals: { for: 55, against: 30 } },
          },
          {
            team: {
              id: 40,
              name: "Liverpool",
              logo: "https://media.api-sports.io/football/teams/40.png",
            },
            points: 82,
            rank: 1,
            all: { win: 25, draw: 7, lose: 3, goals: { for: 75, against: 35 } },
          },
          {
            team: {
              id: 50,
              name: "Manchester City",
              logo: "https://media.api-sports.io/football/teams/50.png",
            },
            points: 80,
            rank: 2,
            all: { win: 24, draw: 8, lose: 3, goals: { for: 72, against: 32 } },
          },
          {
            team: {
              id: 42,
              name: "Arsenal",
              logo: "https://media.api-sports.io/football/teams/42.png",
            },
            points: 78,
            rank: 3,
            all: { win: 24, draw: 6, lose: 5, goals: { for: 70, against: 28 } },
          },
          {
            team: {
              id: 47,
              name: "Tottenham",
              logo: "https://media.api-sports.io/football/teams/47.png",
            },
            points: 57,
            rank: 5,
            all: {
              win: 17,
              draw: 6,
              lose: 12,
              goals: { for: 60, against: 55 },
            },
          },
        ],
      };

      return NextResponse.json(mockApiFootballData);
    } catch (error) {
      return NextResponse.json(
        { error: "데이터를 가져오는 중 오류가 발생했습니다." },
        { status: 500 }
      );
    }
  } else if (league && !mockData[league as keyof typeof mockData]) {
    return NextResponse.json(
      { error: "유효하지 않은 리그 ID입니다." },
      { status: 400 }
    );
  } else if (league) {
    // 기존 목업 데이터 반환
    return NextResponse.json(mockData[league as keyof typeof mockData]);
  }

  return NextResponse.json({ error: "리그 ID가 필요합니다." }, { status: 400 });
}
